//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SastUI.Infraestructura.AccesoDatos.Repositorio
{
    using SastUI.Dominio.Modelo.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SASTEntities : DbContext
    {
        public SASTEntities()
            : base("name=SASTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CABECERA_FICHA> TBL_CABECERA_FICHA { get; set; }
        public virtual DbSet<TBL_CLIENTE> TBL_CLIENTE { get; set; }
        public virtual DbSet<TBL_DETALLE_FICHA> TBL_DETALLE_FICHA { get; set; }
        public virtual DbSet<TBL_EQUIPO> TBL_EQUIPO { get; set; }
        public virtual DbSet<TBL_MARCA> TBL_MARCA { get; set; }
        public virtual DbSet<TBL_MODELO> TBL_MODELO { get; set; }
        public virtual DbSet<TBL_PERFIL> TBL_PERFIL { get; set; }
        public virtual DbSet<TBL_TELEFONO> TBL_TELEFONO { get; set; }
        public virtual DbSet<TBL_TIPO_EQUIPO> TBL_TIPO_EQUIPO { get; set; }
        public virtual DbSet<TBL_TIPO_TELEFONO> TBL_TIPO_TELEFONO { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public virtual DbSet<TBL_AUDITORIA> TBL_AUDITORIA { get; set; }
    }
}
