//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SastUI.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EQUIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_EQUIPO()
        {
            this.TBL_DETALLE_FICHA = new HashSet<TBL_DETALLE_FICHA>();
        }
    
        public int eq_id { get; set; }
        public int tp_id { get; set; }
        public int ma_id { get; set; }
        public int mo_id { get; set; }
        public string eq_serie { get; set; }
        public string eq_so { get; set; }
        public string eq_cartacteristicas { get; set; }
        public string eq_observaciones { get; set; }
        public int eq_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLE_FICHA> TBL_DETALLE_FICHA { get; set; }
        public virtual TBL_MARCA TBL_MARCA { get; set; }
        public virtual TBL_MODELO TBL_MODELO { get; set; }
        public virtual TBL_TIPO_EQUIPO TBL_TIPO_EQUIPO { get; set; }
    }
}
