//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SastUI.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AUDITORIA
    {
        public int au_id { get; set; }
        public int us_id { get; set; }
        public string au_modulo { get; set; }
        public string au_accion { get; set; }
        public string au_valor { get; set; }
        public System.DateTime au_fecha { get; set; }
    }
}
