//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SastUI.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLE_FICHA
    {
        public int df_id { get; set; }
        public int cf_id { get; set; }
        public int eq_id { get; set; }
        public string df_observaciones { get; set; }
        public string df_proceso { get; set; }
        public string df_estado { get; set; }
        public Nullable<System.DateTime> df_fecha_ingreso { get; set; }
        public Nullable<System.DateTime> df_fecha_finalizacion { get; set; }
        public string df_tiempo { get; set; }
    
        public virtual TBL_CABECERA_FICHA TBL_CABECERA_FICHA { get; set; }
        public virtual TBL_EQUIPO TBL_EQUIPO { get; set; }
    }
}
