//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SastUI.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CABECERA_FICHA
    {
        public int cf_id { get; set; }
        public int cl_id { get; set; }
        public int us_id { get; set; }
        public System.DateTime cf_fecha { get; set; }
        public string cf_codigo { get; set; }
        public int cf_estado { get; set; }
    
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual TBL_DETALLE_FICHA TBL_DETALLE_FICHA { get; set; }
    }
}
